blank_issues_enabled: true
contact_links:
  - name: Ask Question
    url: https://github.com/csacanam/lotero-core/discussions/new?category=q-a
    about: Ask questions and discuss Lotero
  - name: Request Feature
    url: https://github.com/csacanam/lotero-core/discussions/new?category=ideas
    about: Request features or share ideas
